### ISSUE TITLE
Sending code to console moves the cursor down two lines, not one

### ISSUE THREAD

**Issue by ReedMerrill** [R-nvim/R.nvim#221]
This issue arose without making any changes to my configuration, and only occurs on MacOS, not linux (Ubuntu). It has been an issue ever since I started using MacOS for work.

Here is an example of what happens. In this example I'm pushing <CR> from the first line while in normal mode.

```r
sqrt(16)   <-- this line is executed
sqrt(4)     <-- this line is skipped
sqrt(36)   <-- the cursor ends up here
```

The cursor ends up on the third line (and, as expected, only the first line was executed). This happens no matter how many lines are in the file (except if it only has one line). 

I would try to look into this myself but I'm not sure where to start.

**Comment by PMassicotte** [comment]
Interesting. Not sure how can this be related to the OS.  Are you runing this in a `.R` file or `.Rmd`/`.qmd` file?

**Comment by ReedMerrill** [comment]
This is happening in `.R` files. I just tried to test it in a `.qmd` file's code chunk but I got an error message about not being in a code chunk (I cane make a separate issue for that).

**Comment by PMassicotte** [comment]
What happens if you put a blank line between all these lines?

**Comment by ReedMerrill** [comment]
The behaviour is the same. The cursor goes down two lines after the current line is sent to the R console. Thanks for investigating!

**Comment by PMassicotte** [comment]
I do not see anything obvious here. Do you remap some keys somewhere else?

**Comment by jalvesaq** [comment]
It's better to set key maps on the `on_filetype` hook (which runs for every buffer) than on the `after_config` hook (called only during the FileType event of the first buffer).

**Comment by ReedMerrill** [comment]
> I do not see anything obvious here. Do you remap some keys somewhere else?

I don't think so. I'll comment again once I find the solution. Perhaps what @jalvesaq is recommending will fix the issue.

**Comment by ReedMerrill** [comment]
I found the solution. I figured <enter> was being called twice, once to send code to the R console, and once for a down motion (the default <enter> behaviour) so I set the noremap option to true on my send line and send selection remaps.

In the config from the readme:

```lua
vim.api.nvim_buf_set_keymap(0, "n", "<enter>", "<Plug>RDSendLine", { noremap = true })
vim.api.nvim_buf_set_keymap(0, "v", "<enter>", "<Plug>RSendSelection", { noremap = true })
```

**Comment by jalvesaq** [comment]
It's important to discover the exact cause of the issue to fix the documentation if necessary. I have this in the options passed to my `R.nvim` config and there is no problem:

```lua
                hook = {
                    on_filetype = function()
                        vim.api.nvim_buf_set_keymap(0, "n", "<Enter>", "<Plug>RDSendLine", {})
                        vim.api.nvim_buf_set_keymap(0, "v", "<Enter>", "<Plug>RSendSelection", {})
                    end,
                },
```

The command `:nmap <Enter>` returns only one command:

```
n  <CR>         @<Plug>RDSendLine
```

**Comment by ReedMerrill** [comment]
After doing some work today, I found that using noremap on the `\<enter\>` binding reduces how much this occurs, but doesn't eliminate the issue. After some testing, I found it depends on the R function that is being called:

```r
print("Hello")         #<-- doesn't skip
print("World")         #<-- doesn't skip
foo <- data.frame(c()) #<-- skips to next foo assignment
print("")              #<-- skips to next foo assignment


foo <- data.frame(c()) #<-- skips to `print("world")
print("Hello")         #<-- doesn't skip
print("World")         #<-- doesn't skip

library(tidyverse)     #<-- skips to `library(tidyverse)`
rm(list = ls())        #<-- skips to `library(tidyverse)`

library(gh)            #<-- skips to `sqrt(4)
print("bar")           #<-- skips to `sqrt(16)
sqrt(4)                #<-- skips to end of file
sqrt(16)               #<-- skips to end of file


```

The behaviour is very inconsistent so I tried to include variation in terms of line spacing and the types of functions.

I also tried using noremap with `\<leader\>r` (an open binding in my config) and the behaviour is the same.

Visual always behaves as expected so until the bug is fixed I will hacked together a remap that uses  `RSendSelection` from normal mode by entering visual mode upon execution.

**Comment by jalvesaq** [comment]
Thanks for the feedback!

**Comment by conig** [comment]
FYI, I was also having this issue but with a different config. Deleting my treesitter cache restored the default behaviour.

**Comment by jalvesaq** [comment]
Thanks, @conig! Feedback from users helps other users to avoid the same issues.

**Comment by ReedMerrill** [comment]
> FYI, I was also having this issue but with a different config. Deleting my treesitter cache restored the default behaviour.

I think my problem was actually at least partially a caching issue too. After deleting the treesitter cache it was resolved, but came back a day layer.

**Comment by Spacecortez** [comment]
> It's important to discover the exact cause of the issue to fix the documentation if necessary. I have this in the options passed to my `R.nvim` config and there is no problem:
> 
> ```lua
>                 hook = {
>                     on_filetype = function()
>                         vim.api.nvim_buf_set_keymap(0, "n", "<Enter>", "<Plug>RDSendLine", {})
>                         vim.api.nvim_buf_set_keymap(0, "v", "<Enter>", "<Plug>RSendSelection", {})
>                     end,
>                 },
> ```
> 
> The command `:nmap <Enter>` returns only one command:
> 
> ```
> n  <CR>         @<Plug>RDSendLine
> ```

I am getting the same problem, and the fixes suggested in this thread haven't fixed the problem for me.

I even tried mapping <Plug>RDSendLine to <C-Space> instead of <Enter>, but I'm still getting a line skipped each time I run the command.

The output for "nmap <Enter>", or "nmap <C-Space>" when I remapped it, was 
> n <Enter>      @<Plug>RDSendLine

Maybe I need to delete my Treesitter cache but I don't know how to do that (or why what would solve the problem).  How do I do that?

Any other ideas / suggestions?

**Comment by Spacecortez** [comment]
If it gives any clues, I've noticed that in other file-types, there is nothing mapped to `<Enter>` but if I hit Enter, or `<C-M>`, or numpad-+, or `<C-Space>` the cursor goes to a new line.

I noticed line-skipping also happens if `<leader>d` is the key mapped to `<Plug>RDSendLine`.

**Comment by Spacecortez** [comment]
I have found a slightly hacky workaround:

> 
> `        vim.api.nvim_buf_set_keymap(0, "v", "<Enter>", "<Plug>RSendSelection", {} )
>         vim.api.nvim_buf_set_keymap(0, "n", "<Enter>", "V<Plug>RSendSelection <ESC>jh", {} )`

**Comment by PMassicotte** [comment]
@Spacecortez If I understand, sending one line will skip the next line?

**Comment by Spacecortez** [comment]
> @Spacecortez If I understand, sending one line will skip the next line?

Thanks for your quick reply!
Yes, as in the OP, sending one line skipped the next line.
I have just tested it again, it skips the next line and then skips any blank or commented lines after that.

So if we have this code, for example:
`
library(tidyverse)
library(knitr)
library(kableExtra)
library(ggforce)
library(scales)

# Basic helper function
smallTable <- function(df, font_size = 11) {
    df |>
        kable("html", escape = F) |>
        kable_styling(font_size = font_size)
}
`

If I start on the first line and hit enter 4 times it'll:

1. Send library(tidyverse) and skip to the kableextra line.
2. Send library(kableextra) and skip to the scales line.
3. Send library(scales) and skip to the smallTable function definition line.
4. Send `smallTable <- function`... line and skip to the `kable("html"`... line.

**Comment by jalvesaq** [comment]
Looking at `R.nvim` source code, we can see that the algorithm is:

1. Move the cursor to the last line of the current expression. For one-line expressions, the cursor should stay on the same line.
2. Move the cursor to the next valid line.

You can test the second step with the following command:

```vim
:lua require("r.cursor").move_next_line()
```

If this command works as expected (move to the next line, not skipping valid lines), then the problem is in the first step.

**Comment by Spacecortez** [comment]
This second step is working as expected for me.

**Comment by jalvesaq** [comment]
Then, we have to look to line 633 of `lua/r/send.lua`:

```lua
        vim.api.nvim_win_set_cursor(0, { math.min(lnum + 1, last_line), 0 })
```

The relevant variable is `lnum` defined by the function `get_code_to_send()`. We can't call it as we did with `move_next_line()` because it's a local function. You would have to debug it yourself by changing the code like this:

```diff
diff --git a/lua/r/send.lua b/lua/r/send.lua
index cd53f49..2a7f939 100644
--- a/lua/r/send.lua
+++ b/lua/r/send.lua
@@ -91,8 +91,11 @@ local function get_code_to_send(txt, row)
     local lines = {}
     local send_insignificant_lines = false
 
+    vim.notify("get_code_to_send: " .. tostring(row) .. " : " .. txt)
+
     -- Find the first non-blank row/column after the cursor ---------------
     while is_insignificant(txt) do
+        vim.notify("is_insignificant: " .. tostring(row) .. " : " .. vim.api.nvim_get_current_line())
         if is_comment(txt) then send_insignificant_lines = true end
         if send_insignificant_lines then table.insert(lines, txt) end
         if row == last_line then return lines, row end
```

I'm using the plugin 'rcarriga/nvim-notify', making it easier to see the output of `vim.notify()`.

**Comment by Spacecortez** [comment]
Output, starting on the first line of the example code [here](https://github.com/R-nvim/R.nvim/issues/221#issuecomment-2472321159), is

```
get_code_to_send: 2 : library(tidyverse)
get_code_to_send: 4 : library(kableExtra)
get_code_to_send: 6 : library(scales)
get_code_to_send: 8 : smallTable <- function(df, font_size = 11) {
```

But there's something odd, in my source code file of send.lua, the line

`        vim.api.nvim_win_set_cursor(0, { math.min(lnum + 1, last_line), 0 })`

is on line 607, not line 633.  Do I have a different version somehow?

**Comment by Spacecortez** [comment]
My config file, loaded with Lazy
```

-- Keymaps from R-nvim source code at /home/max/.local/share/nvim/lazy/R.nvim/lua/r/maps.lua
return {
  "R-nvim/R.nvim",
  lazy = false,
  opts = {
    -- Create a table with the options to be passed to setup()
    R_args = { "--quiet", "--no-save" },
    user_maps_only = true, -- Disable default keymaps
    -- Disable default mappings.  Use :RMapsDesc to see keymaps.
    -- disable_cmds = { "RPackages" }, -- Unfortunately this disables the command entirely
    csv_app = "terminal:vd",
    buffer_opts = "winfixwidth winfixheight", -- By default R terminal buffer is not listed.  I want it listed.
    hook = {
      on_filetype = function()
        -- This function will be called at the FileType event
        -- of files supported by R.nvim. This is an
        -- opportunity to create mappings local to buffers.
        vim.api.nvim_buf_set_keymap(0, "v", "<Enter>", "<Plug>RSendSelection", {} )
        -- vim.api.nvim_buf_set_keymap(0, "n", "<Enter>", "V<Plug>RSendSelection <ESC>j0", {} )
        -- The default function below has a bug where it skips a line of code each time it's executed.
        -- The keymapping above is a workaround
        vim.api.nvim_buf_set_keymap(0, "n", "<Enter>", "<Plug>RDSendLine", {} )

        local wk = require("which-key")
        wk.add({
          mode = "i",
          buffer = true,
            { "<M-->",              "<Plug>RAssign",               desc = "Replace `config.assignment_keymap` with ` <- `" },
            { "<leader>,",          "<Plug>RPipe",                 desc = [[Replace `config.pipe_keymap` with ` |>` (or ` %>%`)]] }
        })
        wk.add({
          mode = "n",
          buffer = true,
          -- { "<leader>a", group = "all" }, --clash
          { "<leader>b", group = "between marks" },
            { "<leader>bb",         "<Plug>RSendMBlock",         desc = "Send to R the lines between two marks" },
            { "<leader>bd",         "<Plug>RDSendMBlock",        desc = "Send to R the lines between two marks and move to next line" },
          { "<leader>c", group = "chunks" }, --clash
            { "<leader>cc",         "<Plug>RSendChunk",          desc = "Send the current chunk of code to R" },
            { "<leader>cd",         "<Plug>RDSendChunk",         desc = "Send to R the current chunk of R code and move down to next chunk" },
            { "<leader>cN",         "<Plug>RPreviousRChunk",     desc = "Go to the previous chunk of R code" },
            { "<leader>cn",         "<Plug>RNextRChunk",         desc = "Go to the next chunk of R code" },
            { "<leader>ch",         "<Plug>RSendChunkFH",        desc = "Send all chunks of R code from the document's begin up to here" },
            { "<leader>cf",         "<Plug>RFormatNumbers",      desc = "Add an 'L' suffix after numbers to explicitly indicate them as integers." },
            { "<leader>cs",         "<Plug>RFormatSubsetting",   desc = "Replace all the `$` subsetting operators with `[[` in the current buffer." },
            -- Wasn't working right for some reason: { "<leader>d",          "<Plug>RDSendLine",          desc = "Send to R the current line and move down to next line" },
          { "<leader>F", group = "functions" },
            { "<leader>Fa",         "<Plug>RSendAllFun",         desc = "Send all the top level functions in the current buffer" },
            { "<leader>Fc",         "<Plug>RSendCurrentFun",     desc = "Send the current function" },
            { "<leader>Fd",         "<Plug>RDSendCurrentFun",    desc = "Send the current function and move the cursor to the end of the function definition" },
          --{ "<leader>g", group = "goto" },
            --                      "<Plug>RSyncFor",            desc = "SyncTeX forward (move from Rnoweb to the corresponding line in the PDF)" },
          { "<leader>k", group = "knit" },
            --                      "<Plug>RBibTeX",             desc = "Sweave the document and run bibtex" },
            --                      "<Plug>RBibTeXK",            desc = "Knit the document, run bibtex and generate the PDF" },
            --                      "<Plug>RSweave",             desc = "Sweave the current document" },
            --                      "<Plug>RMakePDF",            desc = "Sweave the current document and generate a PDF document" },
            --                      "<Plug>RKnitRmCache",        desc = "Delete files from knitr cache" },
            --                      "<Plug>ROpenPDF",            desc = "Open the PDF generated from the current document" },
            { "<leader>ka",         "<Plug>RMakeAll",            desc = "Knit the current document and generate all formats in the header" },
            { "<leader>kh",         "<Plug>RMakeHTML",           desc = "Knit the current document and generate an HTML document" },
            { "<leader>kl",         "<Plug>RMakePDFKb",          desc = "Knit the current document and generate a beamer presentation" },
            { "<leader>kn",         "<Plug>RKnit",               desc = "Knit the document" },
            { "<leader>ko",         "<Plug>RMakeODT",            desc = "Knit the current document and generate an ODT document" },
            { "<leader>kp",         "<Plug>RMakePDFK",           desc = "Knit the current document and generate a PDF document" },
            { "<leader>kr",         "<Plug>RMakeRmd",            desc = "Knit the current document and generate the default document format" },
            { "<leader>kw",         "<Plug>RMakeWord",           desc = "Knit the current document and generate a Word document" },
            { "<leader>l",          "<Plug>RSendLine",           desc = "Send the current line to R" },
            { "<leader>m",          "<Plug>RSendMotion",         desc = "Send to R the lines in a Vim motion" },
            { "<leader>o",          "<Plug>RInsertLineOutput",   desc = "Ask R to evaluate the line and insert the output" },
          { "<leader>p", group = "paragraph" },
            { "<leader>pd",         "<Plug>RDSendParagraph",     desc = "Send to R the next sequence of consecutive non-empty lines" },
            { "<leader>pp",         "<Plug>RSendParagraph",      desc = "Send to R the next consecutive non-empty lines" },
          { "<leader>q", group = "quarto" }, --clash
            { "<leader>qp",         "<Plug>RQuartoPreview",      desc = "Send to R: quarto::quarto_preview()" },
            { "<leader>qr",         "<Plug>RQuartoRender",       desc = "Send to R: quarto::quarto_render()" },
            { "<leader>qs",         "<Plug>RQuartoStop",         desc = "Send to R: quarto::quarto_preview_stop()" },
          { "<leader>r", group = "R"},
            { "<leader>r-",         "<Plug>ROBCloseLists",       desc = "Close S4 objects, lists and data.frames in the Object Browser" },
            { "<leader>r<Left>",    "<Plug>RNLeftPart",          desc = "Send to R the part of the line on the left of the cursor" },
            { "<leader>r<Right>",   "<Plug>RNRightPart",         desc = "Send to R the part of the line on the right of the cursor" },
            { "<leader>r=",         "<Plug>ROBOpenLists",        desc = "Open S4 objects, lists and data.frames in the Object Browser" },
            { "<leader>ra",         "<Plug>RShowArgs",           desc = "Send to R: nvim.args(<cword>)" },
            { "<leader>rb",         "<Plug>RSPlot",              desc = "Send to R command to run summary and plot with <cword> as argument" },
            { "<leader>rc",         "<Plug>RCustomStart",        desc = "Ask user to enter parameters to start R" },
            { "<leader>rd",         "<Plug>RSetwd",              desc = "Send to R setwd(<directory of current document>)" },
            { "<leader>re",         "<Plug>RShowEx",             desc = "Extract the Examples section and paste it in a split window" },
            { "<leader>rf",         "<Plug>RStart",              desc = "Start R with default configuration or reopen terminal window" },
            { "<leader>rg",         "<Plug>RPlot",               desc = "Send to R: plot(<cword>)" },
            { "<leader>rh",         "<Plug>RHelp",               desc = "Ask for R documentation on the object under cursor" },
            { "<leader>ri",         "<Plug>RPackages",           desc = "Install R Packages" },
            { "<leader>rl",         "<Plug>RListSpace",          desc = "Send to R: ls()" },
            { "<leader>rm",         "<Plug>RClearAll",           desc = "Send to R: rm(list   = ls())" },
            { "<leader>rn",         "<Plug>RObjectNames",        desc = "Send to R: nvim.names(<cword>)" },
            { "<leader>ro",         "<Plug>ROBToggle",           desc = "Toggle the Object Browser" },
            { "<leader>rp",         "<Plug>RObjectPr",           desc = "Send to R: print(<cword>)" },
            { "<leader>rq",         "<Plug>RClose",              desc = "Send to R: quit(save = 'no')" },
            { "<leader>rr",         "<Plug>RClearConsole",       desc = "Send to R: <Ctrl-L>" },
            { "<leader>rs",         "<Plug>RSummary",            desc = "Send to R: summary(<cword>)" },
            { "<leader>rt",         "<Plug>RObjectStr",          desc = "Send to R: str(<cword>)" },
            { "<leader>rv",         "<Plug>RViewDF",             desc = "View the data.frame or matrix under cursor in a new tab" },
            { "<leader>rw",         "<Plug>RSaveClose",          desc = "Quit R, saving the workspace" },
          { "<leader>s", group = "split or send" }, --clash
            { "<leader>sc",         "<Plug>RSendChain",          desc = "Send to R the above chain of piped commands" },
            { "<leader>sd",         "<Plug>RDSendSelection",     desc = "Send to R visually selected lines or part of a line" },
            { "<leader>sp",         "<Plug>RSeparatePath",       desc = "Split the file path or the url under the cursor" },
            { "<leader>ss",         "<Plug>RSendSelection",      desc = "Send visually selected lines of part of a line" },
            --                      "<Plug>RSendAboveLines",     desc = "Send to R all lines above the current one" },
            --                      "<Plug>RSendFile",           desc = "Send the whole file to R" },
            --                      "<Plug>RSendLAndOpenNewOne", desc = "Send the current line and open a new one" },
            --                      "<Plug>RShowRout",           desc = "R CMD BATCH the current document and show the output in a new tab" },
            --                      "<Plug>RILeftPart",          desc = "Send to R the part of the line on the left of the cursor" },
            --                      "<Plug>RIRightPart",         desc = "Send to R the part of the line on the right of the cursor" },
          { "<leader>t", group = "terminal" },
            { "<leader>td",         "<Plug>RDputObj",            desc = "Run dput(<cword>) and show the output in a new tab" },
          { "<leader>v", group = "view" },
            --                      "<Plug>RViewDFa",            desc = "View the head of a data.frame or matrix under cursor in a split window" },
            --                      "<Plug>RViewDFs",            desc = "View the data.frame or matrix under cursor in a split window" },
            --                      "<Plug>RViewDFv",            desc = "View the data.frame or matrix under cursor in a vertically split window" },


        })
      end,
    },
    pdfviewer = "zathura",
  },
  config = function(_, opts)
    vim.g.rout_follow_colorscheme = true
    require("r").setup(opts)
    require("r.pdf.generic").open = vim.ui.open
  end,
}
```

**Comment by Spacecortez** [comment]
I undid the debugging changes, ran `:Lazy` then selected R.nvim and ran `Update`, and now the problem is fixed.

I feel a bit silly, I thought that plugins don't need manual updating with Lazy.

**Comment by jalvesaq** [comment]
It's good to know the bug disappeared. Thanks for the feedback!
Perhaps you have done something manually in the `R.nvim` directory which has prevented `lazy.nvim` of updating it.

**Comment by Spacecortez** [comment]
Perhaps when I copied the keybindings from the source code I accidentally saved a change to one of the files.  Sorry for wasting your time!

**Comment by PMassicotte** [comment]
Glad you found the issue!

**Comment by ReedMerrill** [comment]
I am on the most recent commit of the main branch (0115fee) and still encounter the bug, but inconsistently. My session starts off working properly, then at some point the bug behavior begins. My suspicion is that it has something to do with treesitter, assuming that the algorithms used to determine what code to send to the REPL uses it.

**Comment by fbearoff** [comment]
Got the same issue, only happens for code on the first line of the document when there is an empty line after the second entry. I've tried to illustrate this below. I first noticed it on my config, but was able to reproduce with the minimal config. 

Bugged behavior
```R
1 print("Foo")  <- cursor here
2 print("Bar")
3
4 print("Baz")  <- cursor jumps here

-------------------
"Foo" printed
```

```R           
1 print("Foo") <- cursor here
2 print("Bar") 
3              <- cursor jumps here
-------------------
"Foo" printed
```
Correct behavior
```R
1              <- cursor here
2 print("Foo")  
3 print("Bar") <- cursor jumps here
4
5 print("Baz") 

-------------------
"Foo" printed
```

```R        
1 print("Foo") <- cursor here
2 print("Bar") <- cursor jumps here   
-------------------
"Foo" printed
```

**Comment by PMassicotte** [comment]
@jalvesaq I have the same. Also the same if the first line of a code chunk in a qmd/rmd document. I will work on it.

**Comment by PMassicotte** [comment]
For this R code

```r
x <- 1L
y <- 2L
z <- 3L
```

The corresponding tree is

```
(program ; [0, 0] - [3, 0]
  (binary_operator ; [0, 0] - [0, 7]
    lhs: (identifier) ; [0, 0] - [0, 1]
    rhs: (integer)) ; [0, 5] - [0, 7]
  (binary_operator ; [1, 0] - [1, 7]
    lhs: (identifier) ; [1, 0] - [1, 1]
    rhs: (integer)) ; [1, 5] - [1, 7]
  (binary_operator ; [2, 0] - [2, 7]
    lhs: (identifier) ; [2, 0] - [2, 1]
    rhs: (integer))) ; [2, 5] - [2, 7]
```

with nvim 0.10.2, when the cursor is placed on `x`, this is line 3 in the tree that is selected

![image](https://github.com/user-attachments/assets/c88a2eac-120e-43b7-b19d-496071a6741e)

However, on nvim 0.11, the selected node is `program`

![image](https://github.com/user-attachments/assets/f4d6e78e-4b6e-4176-a51e-c95f9d78ef15)

**Comment by PMassicotte** [comment]
Opened an issue on nvim-treesitter https://github.com/nvim-treesitter/nvim-treesitter/issues/7437

**Comment by fbearoff** [comment]
> I found that this bug only appears with the nightly version. Works fine with nvim v0.10.2.

I am experiencing this on v0.10.2-2 in the arch "extra" repository

**Comment by PMassicotte** [comment]
> > I found that this bug only appears with the nightly version. Works fine with nvim v0.10.2.
> 
> I am experiencing this on v0.10.2-2 in the arch "extra" repository

Do you mean it works on 0.12.2-2?

**Comment by fbearoff** [comment]
> > > I found that this bug only appears with the nightly version. Works fine with nvim v0.10.2.
> > 
> > 
> > I am experiencing this on v0.10.2-2 in the arch "extra" repository
> 
> Do you mean it works on 0.12.2-2?

I am only using the stable branch, currently v0.10.2-2 in arch/extra, and I get the bug. I haven't tried nightly.

**Comment by PMassicotte** [comment]
I have found faulty commit https://github.com/neovim/neovim/commit/865ba42e0401043836bca567b4add164c5c46e6f,  this one is working https://github.com/neovim/neovim/commit/3d1e6c56f08f420c0d91ffbee888c05b20806a5e. @jalvesaq are you able to reproduce that?

**Comment by PMassicotte** [comment]
Opened an issue on nvim as advised https://github.com/neovim/neovim/issues/31447

**Comment by jalvesaq** [comment]
I don't have access to my notebook today.

**Comment by jalvesaq** [comment]
> Bugged behavior

I can replicate the bug now.

**Comment by jalvesaq** [comment]
Thanks @khughitt ! I think it's time to remove the recommendation to use `R.nvim` 0.1.0 since the current development version is more stable than it.
